easy_admin:
    site_name: IQ Support
    entities:
        User:
            class: App\Entity\User
            label: "Gebruikers"
            list:
                title: "Meest recente gebruikers"
                fields:
                    - id
                    - organisation.name
                    - role.name
                    - username
                    - email
            form:
                fields:
                    - organisation
                    - role
                    - username
                    - password
                    - email

        Area:
            class: App\Entity\Area
        Building:
            class: App\Entity\Building
        Discipline:
            class: App\Entity\Discipline
        Document:
            class: App\Entity\Document
            label: "Documenten"
            list:
                fields:
                    - file_name
                    - { property: 'file_name', template: 'previews/pdf_preview.html.twig', base_path: '%app.path.documents%' }
                    - discipline
                    - description
            form:
                fields:
                    - file_name
                    - { property: 'file_content', type: 'file' }
                    - discipline
                    - description
        Organisation:
            class: App\Entity\Organisation
        Role:
            class: App\Entity\Role
