easy_admin:
    site_name: IQ Support
    entities:
        User:
            class: App\Entity\User
            label: "Gebruikers"
            list:
                title: "Meest recente gebruikers"
                fields:
                    - id
                    - organisation.name
                    - role.name
                    - username
                    - email
            form:
                fields:
                    - organisation
                    - role
                    - username
                    - password
                    - email

        Area:
            class: App\Entity\Area
        Building:
            class: App\Entity\Building
        Discipline:
            class: App\Entity\Discipline
        Document:
            class: App\Entity\Document
        Organisation:
            class: App\Entity\Organisation
        Role:
            class: App\Entity\Role
