easy_admin:
    site_name: IQ Support
    entities:
        User:
            class: App\Entity\User
            label: "Gebruikers"
            list:
                title: "Gebruikers"
                fields:
                    - id
                    - username
                    - { property: 'organisation.name', label: 'Organisatie' }
                    - { property: 'role', label: "Rol" }
                    - {property: 'email', label: 'E-mail' }
                    - { property: 'suspended', label: 'Geblokkeerd'}
            form:
                fields:
                    - { type: 'section', label: 'Informatie' }
                    - { property: 'organisation', label: 'Organisatie', type_options: { required: true }}
                    - { property: 'username', label: 'Username' }
                    - { property: 'role', type: 'choice', type_options: { choices: { 'Administrator': 'ROLE_ADMIN', 'Leverancier': 'ROLE_LEVERANCIER', 'Opdrachtgever': 'ROLE_OPDRACHTGEVER'}}}
                    - { property: 'email', type: 'email' }
                    - { property: 'suspended', label: 'Geblokkeerd'}
                    - { type: 'section', label: 'Password'}
                    - { property : 'password', type: 'repeated', type_options: { type: Symfony\Component\Form\Extension\Core\Type\PasswordType, invalid_message: 'Passwords do not match',  required: false, first_options: {label: 'Password'}, second_options: {label: 'Password confirmation'} } }

        Area:
            class: App\Entity\Area
            label: "Gebouwdeel"
        Building:
            class: App\Entity\Building
            label: "Gebouw"
            form:
                fields:
                    - name
                    - code
                    - description
                    - { property: 'location', }
        Location:
            class: App\Entity\Location
            label: "Locatie"
        Discipline:
            class: App\Entity\Discipline
        Document:
            class: App\Entity\Document
            label: "Documenten"
            list:
                fields:
                    - id
                    - filename
                    - { property: file_name, label: 'filename' }
                    - discipline
                    - building
                    - floor
                    - documentType
            form:
                fields:
                    - { property: 'file_content', label: 'DWG bestand', type: 'vich_file', type_options: { required: true }}
                    - { property: 'pdf_file', label: 'PDF bestand', type: 'vich_file', type_options: { required: true }}
                    - { property: 'description', label: 'Omschrijving document', type: 'textarea' }
                    - { property: 'location', label: 'Locatie', type_options: { required: true }}
                    - { property: 'building', label: 'Gebouw', type_options: { required: true }}
                    - { property: 'floor', label: 'Verdieping' }
                    - { property: 'area', label: 'Gebouwdeel' }
                    - { property: 'discipline', type_options: { required: true } }
                    - { property: 'documentType', label: 'Document type', type_options: { required: true } }
                    - { property: 'version', label: 'versie', type_options: { required: true } }
            edit:
                fields:
                    - { property: 'file_content', type: 'vich_file', type_options: { required: false }}
                    - { property: 'pdf_file', type: 'vich_file', type_options: { required: false }}
                    - description
                    - location
                    - building
                    - floor
                    - area
                    - { property: 'discipline', type_options: { required: true } }
                    - { property: 'documentType', type_options: { required: true } }
                    - { property: 'version', type_options: { required: true } }
        Organisation:
            list_actions: ['edit', 'show']
            class: App\Entity\Organisation
            label: "Organisatie"
            form:
                fields:
                    - { property: 'name', type: 'text'}
                    - { property: 'logoContent', type: 'vich_file', label: 'Logo'}
                    - { property: 'color', type: 'color' }
            list:
                fields:
                    - { property: 'name', type: 'text'}
                    - { property: 'logoFileName', type: 'image', label: 'Logo', base_path: '%app.path.logos%' }
        Draft:
            class: App\Entity\DocumentDraft
            label: "Ingediende tekeningen"
        DocumentHistory:
            class: App\Entity\DocumentHistory
            label: "Document revisie"
        Issue:
            class: App\Entity\Issue
            label: "Openstaande tekeningen"

    design:
        brand_color: '#e6382f'
        form_theme:
            - 'form_div_layout.html.twig'
            - '@EasyAdmin/form/bootstrap_4.html.twig'
