easy_admin:
    site_name: IQ Support
    entities:
        User:
            class: App\Entity\User
            label: "Users"
            list:
                title: "Gebruikers"
                fields:
                    - id
                    - username
                    - { property: 'organisation.name', label: 'Organisation' }
                    - role
                    - email
                    - { property: 'suspended', label: 'Geblokkeerd'}
            form:
                fields:
                    - { type: 'section', label: 'Information' }
                    - { property: 'organisation', label: 'Organisation' }
                    - username
                    - { property: 'role', type: 'choice', type_options: { choices: { 'Administrator': 'ROLE_ADMIN', 'Leverancier': 'ROLE_LEVERANCIER', 'Opdrachtgever': 'ROLE_OPDRACHTGEVER'}}}
                    - { property: 'email', type: 'email' }
                    - { property: 'suspended', label: 'Geblokkeerd'}
                    - { type: 'section', label: 'Password'}
                    - { property : 'password', type: 'repeated', type_options: { type: Symfony\Component\Form\Extension\Core\Type\PasswordType, invalid_message: 'Passwords do not match',  required: false, first_options: {label: 'Password'}, second_options: {label: 'Password confirmation'} } }

        Area:
            class: App\Entity\Area
        Building:
            class: App\Entity\Building
            form:
                fields:
                    - name
                    - code
                    - description
                    - { property: 'location', }
        Location:
            class: App\Entity\Location
        Discipline:
            class: App\Entity\Discipline
        Document:
            class: App\Entity\Document
            label: "Documenten"
            list:
                fields:
                    - id
                    - filename
                    - { property: file_name, label: 'filename' }
                    - discipline
                    - building
                    - floor
                    - documentType
            form:
                fields:
                    - { property: 'file_content', type: 'vich_file', type_options: { required: true }}
                    - { property: 'pdf_file', type: 'vich_file', type_options: { required: true }}
                    - description
                    - location
                    - building
                    - floor
                    - area
                    - { property: 'discipline', type_options: { required: true } }
                    - { property: 'documentType', type_options: { required: true } }
                    - { property: 'version', type_options: { required: true } }
            edit:
                fields:
                    - { property: 'file_content', type: 'vich_file', type_options: { required: false }}
                    - { property: 'pdf_file', type: 'vich_file', type_options: { required: false }}
                    - description
                    - location
                    - building
                    - floor
                    - area
                    - { property: 'discipline', type_options: { required: true } }
                    - { property: 'documentType', type_options: { required: true } }
                    - { property: 'version', type_options: { required: true } }
        Organisation:
            list_actions: ['edit', 'show']
            class: App\Entity\Organisation
            form:
                fields:
                    - { property: 'name', type: 'text'}
                    - { property: 'logoContent', type: 'vich_file', label: 'Logo'}
                    - { property: 'color', type: 'color' }
            list:
                fields:
                    - { property: 'name', type: 'text'}
                    - { property: 'logoFileName', type: 'image', label: 'Logo', base_path: '%app.path.logos%' }
        Draft:
            class: App\Entity\DocumentDraft
        DocumentHistory:
            class: App\Entity\DocumentHistory
        Issue:
            class: App\Entity\Issue

    design:
        brand_color: '#e6382f'
        form_theme:
            - 'form_div_layout.html.twig'
            - '@EasyAdmin/form/bootstrap_4.html.twig'
