easy_admin:
    site_name: IQ Support
    entities:
        User:
            class: App\Entity\User
            label: "Users"
            list:
                title: "Most recent users"
                fields:
                    - id
                    - { property: 'organisation.name', label: 'Organisation' }
                    - role
                    - username
                    - email
            form:
                fields:
                    - { type: 'section', label: 'Information' }
                    - { property: 'organisation', label: 'Organisation' }
                    - username
                    - { property: 'role', type: 'choice', type_options: { choices: { 'Administrator': 'ROLE_ADMIN', 'Leverancier': 'ROLE_LEVERANCIER', 'Opdrachtgever': 'ROLE_OPDRACHTGEVER'}}}
                    - { property: 'email', type: 'email' }
                    - { type: 'section', label: 'Password'}
                    - {'property': 'password', type: 'repeated', type_options: { type: Symfony\Component\Form\Extension\Core\Type\PasswordType, invalid_message: 'Passwords do not match',  required: false, first_options: {label: 'Password'}, second_options: {label: 'Password confirmation'} } }

        Area:
            class: App\Entity\Area
        Building:
            class: App\Entity\Building
        Discipline:
            class: App\Entity\Discipline
        Document:
            class: App\Entity\Document
            label: "Documenten"
            list:
                fields:
                    - id
                    - filename
                    - { property: file_name, label: 'filename' }
                    - { property: 'file_name', template: 'previews/pdf_preview.html.twig', base_path: '%app.path.documents%', label: 'Preview' }
                    - discipline
                    - building
                    - floor
            form:
                fields:
                    - { property: 'file_content', type: 'vich_file' }
                    - discipline
                    - description
                    - floor
                    - building
                    - documentType
        Organisation:
            class: App\Entity\Organisation

    design:
        form_theme:
            - 'form_div_layout.html.twig'
            - '@EasyAdmin/form/bootstrap_4.html.twig'
