vich_uploader:
    db_driver: orm

    mappings:
        file_content:
            uri_prefix: '%app.path.documents%'
            upload_destination: '%kernel.project_dir%/public%app.path.documents%'
