vich_uploader:
    db_driver: orm

    mappings:
        documents:
            uri_prefix: '%app.path.documents%'
            upload_destination: '%kernel.project_dir%/public%app.path.documents%'
            namer: App\Service\DocumentNamer
        drafts:
            uri_prefix: '%app.path.drafts%'
            upload_destination: '%kernel.project_dir%/public%app.path.drafts%'
            namer: App\Service\DraftNamer
