vich_uploader:
    db_driver: orm

    mappings:
        documents:
            uri_prefix: '%app.path.documents%'
            upload_destination: '%document_upload_directory%'
            namer: App\Service\DocumentNamer
        pdf:
            uri_prefix: '%app.path.documents%'
            upload_destination: '%pdf_upload_directory%'
            namer: App\Service\PDFNamer
        drafts:
            uri_prefix: '%app.path.drafts%'
            upload_destination: '%draft_upload_directory%'
            namer: App\Service\DraftNamer
        logos:
            uri_prefix: '%app.path.logos%'
            upload_destination: '%logo_upload_directory%'
